spring:
  cloud:
    gateway:
      routes:
        - id: book-api
          uri: lb://book-server
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book/v3/api-docs, /v3/api-docs
      x-forwarded:
        prefix-enabled: false

knife4j:
  gateway:
    enabled: true
    routes:
      - name: book-api
        service-name: book-api
        url: /book/v3/api-docs
